# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.28.1/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.28.1/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/Users/jamessquires/Music Dev/test_sc_plugin_cookie/hardclipadaa"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/Users/jamessquires/Music Dev/test_sc_plugin_cookie/hardclipadaa"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/opt/homebrew/Cellar/cmake/3.28.1/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.28.1/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.28.1/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/Cellar/cmake/3.28.1/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/Cellar/cmake/3.28.1/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/Cellar/cmake/3.28.1/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/Cellar/cmake/3.28.1/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/Cellar/cmake/3.28.1/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/Cellar/cmake/3.28.1/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/jamessquires/Music Dev/test_sc_plugin_cookie/hardclipadaa/CMakeFiles" "/Users/jamessquires/Music Dev/test_sc_plugin_cookie/hardclipadaa//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/jamessquires/Music Dev/test_sc_plugin_cookie/hardclipadaa/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named HardClipADAA_scsynth

# Build rule for target.
HardClipADAA_scsynth: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 HardClipADAA_scsynth
.PHONY : HardClipADAA_scsynth

# fast build rule for target.
HardClipADAA_scsynth/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HardClipADAA_scsynth.dir/build.make CMakeFiles/HardClipADAA_scsynth.dir/build
.PHONY : HardClipADAA_scsynth/fast

#=============================================================================
# Target rules for targets named HardClipADAA_supernova

# Build rule for target.
HardClipADAA_supernova: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 HardClipADAA_supernova
.PHONY : HardClipADAA_supernova

# fast build rule for target.
HardClipADAA_supernova/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HardClipADAA_supernova.dir/build.make CMakeFiles/HardClipADAA_supernova.dir/build
.PHONY : HardClipADAA_supernova/fast

#=============================================================================
# Target rules for targets named FIRFilterTests

# Build rule for target.
FIRFilterTests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 FIRFilterTests
.PHONY : FIRFilterTests

# fast build rule for target.
FIRFilterTests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FIRFilterTests.dir/build.make CMakeFiles/FIRFilterTests.dir/build
.PHONY : FIRFilterTests/fast

#=============================================================================
# Target rules for targets named gmock

# Build rule for target.
gmock: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock
.PHONY : gmock

# fast build rule for target.
gmock/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googlemock/CMakeFiles/gmock.dir/build.make _deps/googletest-build/googlemock/CMakeFiles/gmock.dir/build
.PHONY : gmock/fast

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googlemock/CMakeFiles/gmock_main.dir/build.make _deps/googletest-build/googlemock/CMakeFiles/gmock_main.dir/build
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googletest/CMakeFiles/gtest.dir/build.make _deps/googletest-build/googletest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googletest/CMakeFiles/gtest_main.dir/build.make _deps/googletest-build/googletest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

plugins/HardClipADAA/FilterDesign.o: plugins/HardClipADAA/FilterDesign.cpp.o
.PHONY : plugins/HardClipADAA/FilterDesign.o

# target to build an object file
plugins/HardClipADAA/FilterDesign.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HardClipADAA_scsynth.dir/build.make CMakeFiles/HardClipADAA_scsynth.dir/plugins/HardClipADAA/FilterDesign.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HardClipADAA_supernova.dir/build.make CMakeFiles/HardClipADAA_supernova.dir/plugins/HardClipADAA/FilterDesign.cpp.o
.PHONY : plugins/HardClipADAA/FilterDesign.cpp.o

plugins/HardClipADAA/FilterDesign.i: plugins/HardClipADAA/FilterDesign.cpp.i
.PHONY : plugins/HardClipADAA/FilterDesign.i

# target to preprocess a source file
plugins/HardClipADAA/FilterDesign.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HardClipADAA_scsynth.dir/build.make CMakeFiles/HardClipADAA_scsynth.dir/plugins/HardClipADAA/FilterDesign.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HardClipADAA_supernova.dir/build.make CMakeFiles/HardClipADAA_supernova.dir/plugins/HardClipADAA/FilterDesign.cpp.i
.PHONY : plugins/HardClipADAA/FilterDesign.cpp.i

plugins/HardClipADAA/FilterDesign.s: plugins/HardClipADAA/FilterDesign.cpp.s
.PHONY : plugins/HardClipADAA/FilterDesign.s

# target to generate assembly for a file
plugins/HardClipADAA/FilterDesign.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HardClipADAA_scsynth.dir/build.make CMakeFiles/HardClipADAA_scsynth.dir/plugins/HardClipADAA/FilterDesign.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HardClipADAA_supernova.dir/build.make CMakeFiles/HardClipADAA_supernova.dir/plugins/HardClipADAA/FilterDesign.cpp.s
.PHONY : plugins/HardClipADAA/FilterDesign.cpp.s

plugins/HardClipADAA/HardClipADAA.o: plugins/HardClipADAA/HardClipADAA.cpp.o
.PHONY : plugins/HardClipADAA/HardClipADAA.o

# target to build an object file
plugins/HardClipADAA/HardClipADAA.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HardClipADAA_scsynth.dir/build.make CMakeFiles/HardClipADAA_scsynth.dir/plugins/HardClipADAA/HardClipADAA.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HardClipADAA_supernova.dir/build.make CMakeFiles/HardClipADAA_supernova.dir/plugins/HardClipADAA/HardClipADAA.cpp.o
.PHONY : plugins/HardClipADAA/HardClipADAA.cpp.o

plugins/HardClipADAA/HardClipADAA.i: plugins/HardClipADAA/HardClipADAA.cpp.i
.PHONY : plugins/HardClipADAA/HardClipADAA.i

# target to preprocess a source file
plugins/HardClipADAA/HardClipADAA.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HardClipADAA_scsynth.dir/build.make CMakeFiles/HardClipADAA_scsynth.dir/plugins/HardClipADAA/HardClipADAA.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HardClipADAA_supernova.dir/build.make CMakeFiles/HardClipADAA_supernova.dir/plugins/HardClipADAA/HardClipADAA.cpp.i
.PHONY : plugins/HardClipADAA/HardClipADAA.cpp.i

plugins/HardClipADAA/HardClipADAA.s: plugins/HardClipADAA/HardClipADAA.cpp.s
.PHONY : plugins/HardClipADAA/HardClipADAA.s

# target to generate assembly for a file
plugins/HardClipADAA/HardClipADAA.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HardClipADAA_scsynth.dir/build.make CMakeFiles/HardClipADAA_scsynth.dir/plugins/HardClipADAA/HardClipADAA.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HardClipADAA_supernova.dir/build.make CMakeFiles/HardClipADAA_supernova.dir/plugins/HardClipADAA/HardClipADAA.cpp.s
.PHONY : plugins/HardClipADAA/HardClipADAA.cpp.s

plugins/HardClipADAA/Li2.o: plugins/HardClipADAA/Li2.cpp.o
.PHONY : plugins/HardClipADAA/Li2.o

# target to build an object file
plugins/HardClipADAA/Li2.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HardClipADAA_scsynth.dir/build.make CMakeFiles/HardClipADAA_scsynth.dir/plugins/HardClipADAA/Li2.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HardClipADAA_supernova.dir/build.make CMakeFiles/HardClipADAA_supernova.dir/plugins/HardClipADAA/Li2.cpp.o
.PHONY : plugins/HardClipADAA/Li2.cpp.o

plugins/HardClipADAA/Li2.i: plugins/HardClipADAA/Li2.cpp.i
.PHONY : plugins/HardClipADAA/Li2.i

# target to preprocess a source file
plugins/HardClipADAA/Li2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HardClipADAA_scsynth.dir/build.make CMakeFiles/HardClipADAA_scsynth.dir/plugins/HardClipADAA/Li2.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HardClipADAA_supernova.dir/build.make CMakeFiles/HardClipADAA_supernova.dir/plugins/HardClipADAA/Li2.cpp.i
.PHONY : plugins/HardClipADAA/Li2.cpp.i

plugins/HardClipADAA/Li2.s: plugins/HardClipADAA/Li2.cpp.s
.PHONY : plugins/HardClipADAA/Li2.s

# target to generate assembly for a file
plugins/HardClipADAA/Li2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HardClipADAA_scsynth.dir/build.make CMakeFiles/HardClipADAA_scsynth.dir/plugins/HardClipADAA/Li2.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HardClipADAA_supernova.dir/build.make CMakeFiles/HardClipADAA_supernova.dir/plugins/HardClipADAA/Li2.cpp.s
.PHONY : plugins/HardClipADAA/Li2.cpp.s

plugins/HardClipADAA/Oversampling.o: plugins/HardClipADAA/Oversampling.cpp.o
.PHONY : plugins/HardClipADAA/Oversampling.o

# target to build an object file
plugins/HardClipADAA/Oversampling.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HardClipADAA_scsynth.dir/build.make CMakeFiles/HardClipADAA_scsynth.dir/plugins/HardClipADAA/Oversampling.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HardClipADAA_supernova.dir/build.make CMakeFiles/HardClipADAA_supernova.dir/plugins/HardClipADAA/Oversampling.cpp.o
.PHONY : plugins/HardClipADAA/Oversampling.cpp.o

plugins/HardClipADAA/Oversampling.i: plugins/HardClipADAA/Oversampling.cpp.i
.PHONY : plugins/HardClipADAA/Oversampling.i

# target to preprocess a source file
plugins/HardClipADAA/Oversampling.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HardClipADAA_scsynth.dir/build.make CMakeFiles/HardClipADAA_scsynth.dir/plugins/HardClipADAA/Oversampling.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HardClipADAA_supernova.dir/build.make CMakeFiles/HardClipADAA_supernova.dir/plugins/HardClipADAA/Oversampling.cpp.i
.PHONY : plugins/HardClipADAA/Oversampling.cpp.i

plugins/HardClipADAA/Oversampling.s: plugins/HardClipADAA/Oversampling.cpp.s
.PHONY : plugins/HardClipADAA/Oversampling.s

# target to generate assembly for a file
plugins/HardClipADAA/Oversampling.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HardClipADAA_scsynth.dir/build.make CMakeFiles/HardClipADAA_scsynth.dir/plugins/HardClipADAA/Oversampling.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HardClipADAA_supernova.dir/build.make CMakeFiles/HardClipADAA_supernova.dir/plugins/HardClipADAA/Oversampling.cpp.s
.PHONY : plugins/HardClipADAA/Oversampling.cpp.s

tests/FIRFilterTests.o: tests/FIRFilterTests.cpp.o
.PHONY : tests/FIRFilterTests.o

# target to build an object file
tests/FIRFilterTests.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FIRFilterTests.dir/build.make CMakeFiles/FIRFilterTests.dir/tests/FIRFilterTests.cpp.o
.PHONY : tests/FIRFilterTests.cpp.o

tests/FIRFilterTests.i: tests/FIRFilterTests.cpp.i
.PHONY : tests/FIRFilterTests.i

# target to preprocess a source file
tests/FIRFilterTests.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FIRFilterTests.dir/build.make CMakeFiles/FIRFilterTests.dir/tests/FIRFilterTests.cpp.i
.PHONY : tests/FIRFilterTests.cpp.i

tests/FIRFilterTests.s: tests/FIRFilterTests.cpp.s
.PHONY : tests/FIRFilterTests.s

# target to generate assembly for a file
tests/FIRFilterTests.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FIRFilterTests.dir/build.make CMakeFiles/FIRFilterTests.dir/tests/FIRFilterTests.cpp.s
.PHONY : tests/FIRFilterTests.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... FIRFilterTests"
	@echo "... HardClipADAA_scsynth"
	@echo "... HardClipADAA_supernova"
	@echo "... gmock"
	@echo "... gmock_main"
	@echo "... gtest"
	@echo "... gtest_main"
	@echo "... plugins/HardClipADAA/FilterDesign.o"
	@echo "... plugins/HardClipADAA/FilterDesign.i"
	@echo "... plugins/HardClipADAA/FilterDesign.s"
	@echo "... plugins/HardClipADAA/HardClipADAA.o"
	@echo "... plugins/HardClipADAA/HardClipADAA.i"
	@echo "... plugins/HardClipADAA/HardClipADAA.s"
	@echo "... plugins/HardClipADAA/Li2.o"
	@echo "... plugins/HardClipADAA/Li2.i"
	@echo "... plugins/HardClipADAA/Li2.s"
	@echo "... plugins/HardClipADAA/Oversampling.o"
	@echo "... plugins/HardClipADAA/Oversampling.i"
	@echo "... plugins/HardClipADAA/Oversampling.s"
	@echo "... tests/FIRFilterTests.o"
	@echo "... tests/FIRFilterTests.i"
	@echo "... tests/FIRFilterTests.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

